### ISSUE TITLE
Default user and password invalid

### ISSUE THREAD

**Issue by antuelle78** [ansible/eda-server#226]
Hi,

I followed the instructions for deploying the dev environment: https://github.com/ansible/eda-server#1-clone-the-repository

I get to the web interface but I am unable to login with the username: dev_user@redhat.com and password: none2tuff

Any pointers on what I might be missing.

![image](https://user-images.githubusercontent.com/37155439/197407634-c48f4b66-51b4-4e49-b3a2-1bd805a9339d.png)

**Comment by Alex-Izquierdo** [comment]
Hi @antuelle78 Could you provide more info about what commands have you executed and what is their output?

**Comment by antuelle78** [comment]
@Alex-Izquierdo 
Here the steps:
git clone https://github.com/ansible/eda-server.git
cd eda-server

python -m venv .venv
source .venv/bin/activate
pip install -e .

pip install ansible
ansible-galaxy collection install ansible.eda

task dev:all:start
task dev:user:add

**Comment by ttuffin** [comment]
Hi @antuelle78, I am unable to reproduce this issue. Can you please run a fresh deployment and post the output of the `task dev:user:add` command? You should see something like this:
```
$ task dev:user:add
task: [version] scripts/version_check.sh bash
2022-10-26 12:43:20 [INFO	]  Checking bash version...
2022-10-26 12:43:20 [INFO	]  Current version: 5
2022-10-26 12:43:20 [INFO	]  Check successful
task: [dev] scripts/eda_dev.sh add-dev-user
2022-10-26 12:43:20 [INFO	]  Adding dev user: dev_user@redhat.com, pass: none2tuff
WARNING: Specifying passwords in command line arguments is insecure.
INFO: User cdbe633a-d902-4fa4-97a4-6a9c662b564e has registered.
```
