### ISSUE TITLE
Allow disabling SSL verification to clone project from private repository over HTTPS with self-signed certificate

### ISSUE THREAD

**Issue by kurokobo** [ansible/eda-server#337]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/aap-eda/issues) for duplicates.
- [X] I understand that EDA-Controller is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Currently, there is no feature to disable SSL verification for remote git repository to clone project.

Of course, disabling SSL verification is not recommended from a security perspective, and I understand that adding certificates to the worker container's certificate store would be ideal, but disabling SSL verification for development and testing EDA/EDA Controller purposes is in demand.

For `git` command, an environment variable `GIT_SSL_NO_VERIFY` can be used to disable SSL verification.
But in the current implementation, even if we add this environment variables to worker container, it is ignored due to explicit `env` args for `subprocess.run`:

https://github.com/ansible/eda-server/blob/8fab57467d40504882709ea6d099b7a0ecfba16b/src/aap_eda/services/project/git.py#L142-L144

https://github.com/ansible/eda-server/blob/8fab57467d40504882709ea6d099b7a0ecfba16b/src/aap_eda/services/project/git.py#L163-L173

### Steps to reproduce

1. Deploy EDA Controller with worker that has `GIT_SSL_NO_VERIFY=1` as its environment variable
2. Push rulebooks to the remote repository that uses self-signed certificate over HTTPS
3. Add project with the remote repository in EDA Controller
4. Try to sync project

### Current results

The project is marked as `Failed` with following error:

```
Command '/usr/bin/git clone --quiet --depth 1 https://git.example.com/gitea/example.git /tmp/eda-project-77tmgvb0/src' returned non-zero exit status 128.
```

The logs from worker pod:

```bash
2023-08-03 13:15:17,947 WARNING  Command returned non-zero exit status 128:
        command: /usr/bin/git clone --quiet --depth 1 https://git.example.com/gitea/example.git /tmp/eda-project-77tmgvb0/src
        stderr: fatal: unable to access 'https://git.example.com/gitea/example.git/': SSL certificate problem: self-signed certificate
```

I can confirm the worker container has the env and the env takes effect for invoking `git clone` manually in the container.

```bash
$ kubectl -n eda exec -it eda-worker-69b97bc457-pbjbf -- bash

[eda@eda-worker-69b97bc457-pbjbf src]$ env | grep GIT_SSL_NO_VERIFY
GIT_SSL_NO_VERIFY=1

[eda@eda-worker-69b97bc457-pbjbf src]$ git clone https://git.example.com/gitea/example.git
Cloning into 'example'...
remote: Enumerating objects: 1417, done.
remote: Counting objects: 100% (1417/1417), done.
remote: Compressing objects: 100% (485/485), done.
remote: Total 1417 (delta 903), reused 1407 (delta 899), pack-reused 0
Receiving objects: 100% (1417/1417), 279.88 KiB | 31.10 MiB/s, done.
Resolving deltas: 100% (903/903), done.

[eda@eda-worker-69b97bc457-pbjbf src]$ rm -rf example

# Remove env and ensure git clone is failed
[eda@eda-worker-69b97bc457-pbjbf src]$ unset GIT_SSL_NO_VERIFY
[eda@eda-worker-69b97bc457-pbjbf src]$ git clone https://git.example.com/gitea/example.git
Cloning into 'example'...
fatal: unable to access 'https://git.example.com/gitea/example.git/': SSL certificate problem: self-signed certificate
```

### Sugested feature result

The environment variable `GIT_SSL_NO_VERIFY` on the worker container can take effect to clone project from the remote repository that uses self-signed certificate over HTTPS.

### Additional information

While it would be best to be able to disable SSL verification on a per-project basis via the GUI, it seems easier to improve the project service to respect the environment variable GIT_SSL_NO_VERIFY if it is specified.

**Comment by Alex-Izquierdo** [comment]
Duplicate: https://github.com/ansible/eda-server/issues/317

**Comment by kurokobo** [comment]
@Alex-Izquierdo
Uh-oh sorry my bad, how embarrassing :confounded:
I've totally forgot about that, thanks for closing!

**Comment by Alex-Izquierdo** [comment]
No problem, @kurokobo, thanks to you for bringing it up.
