### ISSUE TITLE
Adding other SCM authentication methods 

### ISSUE THREAD

**Issue by cidrbl0ck** [ansible/eda-server#461]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/aap-eda/issues) for duplicates.
- [X] I understand that EDA-Controller is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

EDA-Server should support the same authentication mechanisms to SCM (Github) as AWX, Tower, AAP, etc. The limitation of only a non-SSO Personal Access Token is a breaking item for me and my company. Since we use a Github Enterprise account, with security restrictions that include direct SSO ties to Okta, means that I am unable to use the same Github repos for EDA content as I do for controller content. 
My options are either divide things and use a repo source outside my org. Or setup a GH action to copy content from within to outside the org.
Neither of which my boss nor InfoSec would approve of.

### Steps to reproduce

Create repository, create personal access token from service account, create Project and add repo as source. 

### Current results

Project sync fails, in the webgui the error is:

Command '['/usr/bin/git', 'clone', '--quiet', '--depth', '1', 'https://user value here:token value here@github.com/company/aap.git', '/tmp/eda-project-4_1pndwz/src']' returned non-zero exit status 128.

Attempting to run the same command on the EDA host itself results in:

[root@aapedap01 eda]# git clone --depth 1 https://user value here:token value here@github.com/company/aap.git /tmp/eda11122
Cloning into '/tmp/eda11122'...
remote: The 'company' organization has enabled or enforced SAML SSO.
remote: To access this repository, visit https://github.com/orgs/company/sso?authorization_request=auth request string and try your request again.

### Suggested feature result

Adding SCM Private key would be the silver-bullet to this issue

**Comment by iwt-cmd** [comment]
Agreed!  We've standardized on Azure DevOps which means to use EDA we'll need to move/maintain those projects to Github or Gitlab.  The SCM private key suggested above would help match the options in AWX/AAP, especially since EDA needs one of these to function correctly.

**Comment by cidrbl0ck** [comment]
I assume by the lack of maintainer/team input that this sort of ask isn't important.

**Comment by Kentix** [comment]
@RedHat Team - Any thoughts on this? We are also seeking the mentioned functionality; it is critical to us expanding our AAP implementation.

**Comment by Alex-Izquierdo** [comment]
AAP RFE related: https://issues.redhat.com/browse/AAPRFE-825

**Comment by cidrbl0ck** [comment]
Commenting again, The AAP RFE has had no apparent progress and we'd really like to use EDA.

**Comment by Alex-Izquierdo** [comment]
HI @cidrbl0ck Thanks for your feedback. We expect to implement this feature in the upcoming weeks. Just wait a little longer. :)

**Comment by cidrbl0ck** [comment]
@Alex-Izquierdo Thank you! I'd like to ask one more thing but with the full understanding that you likely do not know for sure and don't control it..
This EDA-Server is upstream from RH as I understand, to your knowledge is there any 'normal' or 'average' timeframe whereby changes at this level are reflected at theirs?

**Comment by Alex-Izquierdo** [comment]
Hi @cidrbl0ck The release workflows between RH and the upstream project are different; they are not based on timeframes. Any questions related to the commercial product must be directed through your RH support.
