### ISSUE TITLE
discover rulebooks from both paths (or document first path found and implications)

### ISSUE THREAD

**Issue by watsonb** [ansible/eda-server#465]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/aap-eda/issues) for duplicates.
- [X] I understand that EDA-Controller is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

When importing a project into EDA server, your project may contain the following paths

- ./extensions/eda/rulebooks
- ./rulebooks

On import, if EDA server detects the first path, it attempts to import rulebooks in that path but then ignores the second path.  Hence, if the first path was empty (e.g. a placeholder), EDA would fail to import any rulebooks defined in `./rulebooks`

### Steps to reproduce

1. Create a rulebook project with these paths present, ensuring the first path is absent of any rulebooks.
2. Place rulebooks in the second path (e.g. `./rulebooks`).  
3. Import the project to EDA server
4. Try to create an Activation
5. Discover that none of the rulebooks defined in `./rulebooks` are present
6. Delete the `./extensions/eda/rulebooks` path in your project
7. Commit/push your project
8. Sync the project in EDA
9. Try to create an Activation
10. Discover that the rulebooks defined in `./rulebooks` are now available

### Current results

`./rulebooks` directory is ignored if `./extensions/eda/rulebooks` directory is present.

### Sugested feature result

Either import rulebooks from both paths or provide concise documentation explaining this situation.

**Comment by Alex-Izquierdo** [comment]
Hi @watsonb Thank you very much for your feedback. The `/rulebooks` layout originates from the earliest versions of the application. It's an old path that we've kept for backward compatibility. However, it's slated for deprecation in the future, and we don't have plans to support both paths concurrently. The only supported path is the ansible-collection official one: `/extensions/eda/rulebooks` and I recommend to migrate your projects accordingly. 

Thanks for warning, I will take care that our documentation is properly updated.
