### ISSUE TITLE
Rulebook restart within kubernetes causes rulebooks to become unavailable

### ISSUE THREAD

**Issue by jon-nfc** [ansible/eda-server#616]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/aap-eda/issues) for duplicates.
- [X] I understand that EDA-Controller is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Restarting a rulebook activation has two issues:

- if using kubernetes ingress, you must re-deploy the ingress as the service name has changed

- cluster Internal traffic that uses the service name for rulebook access will also loose access to the rulebook as the address has changed, specifically in this case the service name.

### Environment

Kubernetes

### Steps to reproduce

1. start a rulebook activation
2. check service name `kubectl get svc -n <namespace>`
3. note name
4. restart rulebook activation
5. check service name `kubectl get svc -n <namespace>`
6. bam!!! service name different

### Actual results

Service details before restart

``` bash
root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda
NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
activation-job-6-16-5003                                 ClusterIP   172.16.41.108   <none>        5003/TCP   6m40s
eda-api                                                  ClusterIP   172.16.41.45    <none>        8000/TCP   3d
eda-daphne                                               ClusterIP   172.16.41.171   <none>        8001/TCP   3d
eda-postgres-13                                          ClusterIP   None            <none>        5432/TCP   3d
eda-redis-svc                                            ClusterIP   172.16.40.199   <none>        6379/TCP   3d
eda-server-operator-controller-manager-metrics-service   ClusterIP   172.16.40.153   <none>        8443/TCP   11d
eda-ui                                                   ClusterIP   172.16.41.34    <none>        80/TCP     3d
root@7dd5f0bf32b32b93:/home/deploy# 
root@7dd5f0bf32b32b93:/home/deploy# 
root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda activation-job-6-16-5003 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-19T18:09:20Z"
  labels:
    app: eda
    job-name: activation-job-6-16
  name: activation-job-6-16-5003
  namespace: eda
  resourceVersion: "5870150"
  uid: 780deb98-8f1a-4f15-b843-2437bfddf2b6
spec:
  clusterIP: 172.16.41.108
  clusterIPs:
  - 172.16.41.108
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: eda
    job-name: activation-job-6-16
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

service detais post restart

``` bash

root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda
NAME                                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
activation-job-6-17-5003                                 ClusterIP   172.16.41.68    <none>        5003/TCP   11s
eda-api                                                  ClusterIP   172.16.41.45    <none>        8000/TCP   3d
eda-daphne                                               ClusterIP   172.16.41.171   <none>        8001/TCP   3d
eda-postgres-13                                          ClusterIP   None            <none>        5432/TCP   3d
eda-redis-svc                                            ClusterIP   172.16.40.199   <none>        6379/TCP   3d
eda-server-operator-controller-manager-metrics-service   ClusterIP   172.16.40.153   <none>        8443/TCP   11d
eda-ui                                                   ClusterIP   172.16.41.34    <none>        80/TCP     3d
root@7dd5f0bf32b32b93:/home/deploy# kubectl get svc -n eda activation-job-6-17-5003 -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-19T18:39:58Z"
  labels:
    app: eda
    job-name: activation-job-6-17
  name: activation-job-6-17-5003
  namespace: eda
  resourceVersion: "5886550"
  uid: 5acb12fa-6799-406d-8716-b77c8b7b1c37
spec:
  clusterIP: 172.16.41.68
  clusterIPs:
  - 172.16.41.68
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5003
    protocol: TCP
    targetPort: 5003
  selector:
    app: eda
    job-name: activation-job-6-17
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
root@7dd5f0bf32b32b93:/home/deploy# 

```

### Expected results

That the service name used for the rulebook activation remains the same.  In addition that there also be service labels that remain the same for the service per rulebook so that kubernetes label selectors work.

### Additional information

service name appears to use format   `activation-job-<job-id>-<activation number>-<port>`  i.e.  `activation-job-6-16-5003` dropping the information that is not relevant `<activation number>` and `<port>` would fix 99% of the crux of this issue. This useless "service name" information is better suited to an annotation.

**Comment by Alex-Izquierdo** [comment]
RFE related: https://issues.redhat.com/browse/AAPRFE-821

**Comment by kurokobo** [comment]
@Alex-Izquierdo 
I know it will take much time to fully implement #381, so is it practical to at least have the instance ID eliminated from the service name as a short term workaround, instead of fundamental solution? Simply removing the instance ID from the service name eliminates the need to update Ingress/Route each time the activation is restarted.

It appears that the instance ID had made to be included in the job name by https://github.com/ansible/eda-server/pull/373 and https://github.com/ansible/eda-server/pull/355, but since I don't have permission to read the referenced issue [AAP-13416](https://issues.redhat.com/browse/AAP-13416), I could not determine if the service name change is allowed.

**Comment by Alex-Izquierdo** [comment]
Hi @kurokobo We are already aware of this problem. This needs to be discussed and analyze potential breaking changes and upgrades in running instances.

**Comment by jon-nfc** [comment]
@Alex-Izquierdo 

To prevent the introduction of a breaking change a feature flag could be used. That way only those who expressly want the change have to manually set the feature flag. then have the feature flag introduce a depreciation warning.  i.e.

User sets flag:
1. user sets feature flag i.e. env var `static_service_name=true`
2. rulebook activation service names are now static
3. after version x release of eda, any user that has this flag set,  receives depreciation warning that feature flag no longer used
 
Existing user / flag not set
1. a message is logged to logfile/system, as a depreciation warning

    > feature flag `static_service_name` will be enforced in version x of eda. recommend this flag be set before then to avoid breaking current set-ups.

**Comment by jon-nfc** [comment]
Any update re progressing a solution for this issue?

**Comment by jon-nfc** [comment]
@Alex-Izquierdo 

cheers for the update. TBH I don't know how anyone could use this in production as an activation restart causes a loss of access to the service.

Is there a time frame for the proposed solution? 

I would be happy if a fix could be pushed out that just sets some permanent labels for the pod that remains static even after an activation restart, this way I could create my own service with selectors. setting a label of `activation-<ID>` would be sufficient.

**Comment by benthomasson** [comment]
Are you using a webhook event source plugin?

**Comment by jon-nfc** [comment]
> Are you using a webhook event source plugin?

yes
