### ISSUE TITLE
EDA-server doesn't parse conditions the same exact way as ansible-rulebook

### ISSUE THREAD

**Issue by Glaring-Seagull** [ansible/eda-server#693]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/aap-eda/issues) for duplicates.
- [X] I understand that EDA-Controller is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When writing conditions that use mixed notation in the form of dot notation and bracket notation, the eda-server parser will throw an error and fail to start the rulebook activation, while the ansible-rulebook CLI interface will accept and parse the condition, and start the rulebook activation.

### Environment

Server and Workstation: RHEL 8.8

ansible-rulebook: 1.0.5

Automation Platform: 2.4

### Steps to reproduce

Create a rulebook that contains a condition that uses mixed notation and run it through ansible-rulebook and eda-server. An example of mixed notation would look like, event.payload.changes[0].ref.displayId == 'dev'

### Actual results

The eda-server parser identifies an error at the start of the bracket notation and doesn't start the rulebook activation.

ansible_rulebook.cli - ERROR - Terminating Error parsing: event.payload.changes[0].ref.displayId == 'dev'. Expected end of text, found '['  (at char 21), (line:1, col:22)

### Expected results

The rulebook should start in eda-server like it does for ansible-rulebook.

**Comment by benthomasson** [comment]
Please confirm the version of ansible-rulebook in your decision environment in EDA.   This may be the case of a fix in a newer version of ansible-rulebook and an older version of ansible-rulebook in EDA.

**Comment by bzwei** [comment]
I cannot reproduce the error. I am using a [rulebook](https://github.com/bzwei/rulebooks/commit/6e65f94ad2139e99aff069957e50cc50eaed3e49) with the same condition reported in this issue. The ansible-rulebook CLI I am using is 1.0.5.
